### ISSUE TITLE
Not working with Jellyfin 10.6.1

### ISSUE THREAD

**Issue by Spots28** [nwithan8/Plex2Jellyfin#3]
Hello, 
the migration script from plex to jellyfin isnt working. 

Jellyfins Log:
[ErrorLog Migrate Users.txt](https://github.com/nwithan8/Plex2Jellyfin/files/4987375/ErrorLog.Migrate.Users.txt)

**Comment by nwithan8** [comment]
Thanks for the log. I have an initial idea of what might be wrong and how to fix it.
