### ISSUE TITLE
migrate script won't run

### ISSUE THREAD

**Issue by shaybc** [nwithan8/Plex2Jellyfin#6]
Tring to make the move from plex to JellyFin,

did all the steps, but the "`migrate_playlists.py`" script runs for less then a second and finished with the following results:

```
Authenticating with Jellfin...
Beginning playlist migration...
Playlist migration complete.
```

any idea what am i missing ?

**Comment by nwithan8** [comment]
I'll look into it.

**Comment by nwithan8** [comment]
> Tring to make the move from plex to JellyFin,
> 
> did all the steps, but the "`migrate_playlists.py`" script runs for less then a second and finished with the following results:
> 
> ```
> Authenticating with Jellfin...
> Beginning playlist migration...
> Playlist migration complete.
> ```
> 
> any idea what am i missing ?

It should print out that it's beginning migrating each playlist one by one, printing out the name of each playlist. If it's not, it seems it's not finding your Plex playlists. Are your credentials correct and/or do you have Plex playlists?

**Comment by nwithan8** [comment]
Closing due to no response.
Please respond to reopen.
